// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Activator
        {
            private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IActivatorGetter> xMASMIPlaceTrapActivator => Construct(0x3dcffc);
            public static FormLink<IActivatorGetter> xMASNEDistanceMeasureCaster => Construct(0x66ab6);
            public static FormLink<IActivatorGetter> xMAALTSpellPrismSpellRelay => Construct(0x683ae1);
            public static FormLink<IActivatorGetter> xMASNERope => Construct(0x4e3a0);
            public static FormLink<IActivatorGetter> xMAALTCombatShiftActivator => Construct(0x51f2a);
            public static FormLink<IActivatorGetter> xMASNERope2 => Construct(0x51978);
            public static FormLink<IActivatorGetter> xMAALTKineticShiftActivator => Construct(0x57045);
            public static FormLink<IActivatorGetter> xMAALTPhaseShiftActivator => Construct(0x51f30);
            public static FormLink<IActivatorGetter> xMAALTArtificialSunActivator => Construct(0x70600);
            public static FormLink<IActivatorGetter> xMASNEMeasureDistanceMeasurer => Construct(0x59001);
            public static FormLink<IActivatorGetter> xMASNERopeNonDynamic1 => Construct(0x62e5a);
            public static FormLink<IActivatorGetter> xMADEXInventor2OilContainerActivator => Construct(0x3be995);
            public static FormLink<IActivatorGetter> xMASNERemovableTorch01_OFF => Construct(0x71850);
            public static FormLink<IActivatorGetter> xMASNEFireArrowActivator => Construct(0x8bcbf);
            public static FormLink<IActivatorGetter> xMASNEFireExtinguisher => Construct(0x748ed);
            public static FormLink<IActivatorGetter> xMASNEFireLighter => Construct(0x748ee);
            public static FormLink<IActivatorGetter> xMASNEWaterArrowActivator => Construct(0x88c49);
            public static FormLink<IActivatorGetter> xMAALTInverseShiftActivator => Construct(0x1d333e);
            public static FormLink<IActivatorGetter> xMASNEOilFindGround => Construct(0x92dd7);
            public static FormLink<IActivatorGetter> xMADESFrostFieldActivator => Construct(0x98ef2);
            public static FormLink<IActivatorGetter> xMASNEOilMarker => Construct(0x9da20);
            public static FormLink<IActivatorGetter> xMASNEOilMarkerMaster => Construct(0x9df87);
            public static FormLink<IActivatorGetter> xMACONGatesOfOblivionActivator => Construct(0x17d132);
            public static FormLink<IActivatorGetter> xMAALTSpellPrismActivator => Construct(0x67e9db);
        }
    }
}
