// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Ammunition
        {
            private static FormLink<IAmmunitionGetter> Construct(uint id) => new FormLink<IAmmunitionGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IAmmunitionGetter> xMASNEWaterArrow => Construct(0x6dbce);
            public static FormLink<IAmmunitionGetter> xMASNERopeArrow => Construct(0x4e3a1);
            public static FormLink<IAmmunitionGetter> xMASNEWaterBolt => Construct(0xabc65);
            public static FormLink<IAmmunitionGetter> xMASNERopeBolt => Construct(0xabc64);
            public static FormLink<IAmmunitionGetter> xMASNEOilBolt => Construct(0xabc63);
            public static FormLink<IAmmunitionGetter> xMASNENoisemakerBolt => Construct(0xabc62);
            public static FormLink<IAmmunitionGetter> xMASNEFireBolt => Construct(0xabc61);
            public static FormLink<IAmmunitionGetter> xMASNEOilArrow => Construct(0x91db0);
            public static FormLink<IAmmunitionGetter> xMASNENoisemakerArrow => Construct(0x8d248);
            public static FormLink<IAmmunitionGetter> xMASNEFireArrow => Construct(0x8a734);
        }
    }
}
