// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Armor
        {
            private static FormLink<IArmorGetter> Construct(uint id) => new FormLink<IArmorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IArmorGetter> xMAEasterEggMaskNerjal => Construct(0x6b6509);
            public static FormLink<IArmorGetter> xMACONSkeletonArcherOverlordSkin => Construct(0x4d52ab);
            public static FormLink<IArmorGetter> xMAFakeArmor => Construct(0x49d766);
            public static FormLink<IArmorGetter> xMAENCGreatInfusionDragonSigilArmor => Construct(0x419ca7);
            public static FormLink<IArmorGetter> xMASNEArmorDarkCowl => Construct(0x3af666);
        }
    }
}
