// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class ArmorAddon
        {
            private static FormLink<IArmorAddonGetter> Construct(uint id) => new FormLink<IArmorAddonGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IArmorAddonGetter> xMACONSkeletonArcherOverlordSkinAA => Construct(0x4d52aa);
            public static FormLink<IArmorAddonGetter> xMAEasterEggMaskNerjalAA => Construct(0x6bb60f);
            public static FormLink<IArmorAddonGetter> xMAEasterEggMaskNerjalDefaultAA => Construct(0x6bb611);
            public static FormLink<IArmorAddonGetter> xMASNEMaskAA => Construct(0x3e136);
            public static FormLink<IArmorAddonGetter> xMASNEMaskKhaAA => Construct(0x4de3d);
            public static FormLink<IArmorAddonGetter> xMASNEMaskArgAA => Construct(0x4de3c);
        }
    }
}
