// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Book
        {
            private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IBookGetter> xMADESSpellTomeChillingTouch => Construct(0x251dd8);
            public static FormLink<IBookGetter> xMADESSpellTomeSizzlingTouch => Construct(0x251dd9);
            public static FormLink<IBookGetter> xMADESSpellTomeImplosion => Construct(0x251ddb);
            public static FormLink<IBookGetter> xMADESSpellTomeFrostField => Construct(0x251dde);
            public static FormLink<IBookGetter> xMADESSpellTomeStaticDischarge => Construct(0x251ddf);
            public static FormLink<IBookGetter> xMADESSpellTomeArcticBlaze => Construct(0x251de0);
            public static FormLink<IBookGetter> xMADESSpellTomeTempestCloak => Construct(0x251de1);
            public static FormLink<IBookGetter> xMADESSpellTomePyroelectricOrb => Construct(0x251de2);
            public static FormLink<IBookGetter> xMACONSpellTomeConjureWeakFlameAtronach => Construct(0x2610e8);
            public static FormLink<IBookGetter> xMASpellTomeConjureUnboundFlameAtronach => Construct(0x2610e9);
            public static FormLink<IBookGetter> xMAILLSpellTomeAmnesia => Construct(0x2fe16c);
            public static FormLink<IBookGetter> xMAILLSpellTomeAnarchy => Construct(0x2fe173);
            public static FormLink<IBookGetter> xMADESSpellTomeCharredSkin => Construct(0x30328a);
            public static FormLink<IBookGetter> xMADESSpellTomeStaticSkin => Construct(0x30328c);
            public static FormLink<IBookGetter> xMADESSpellTomeCrystalSkin => Construct(0x30328d);
            public static FormLink<IBookGetter> xMADESSpellTomePrismaticBeam => Construct(0x30d499);
            public static FormLink<IBookGetter> xMAEasterEggClawsOfTheCrab => Construct(0x35430b);
            public static FormLink<IBookGetter> xMASpellTomeAccelerate => Construct(0x502bed);
            public static FormLink<IBookGetter> xMASpellTomeHellfireCage => Construct(0x502bf7);
            public static FormLink<IBookGetter> xMADESSpellTomeHeavyFireball => Construct(0x507cfd);
            public static FormLink<IBookGetter> xMASpellTomeGreatThundercall => Construct(0x507d1d);
            public static FormLink<IBookGetter> xMASpellTomeFrostburn => Construct(0x52b44a);
            public static FormLink<IBookGetter> xMASpellTomeCorrodingTouch => Construct(0x530553);
            public static FormLink<IBookGetter> xMASpellTomePrismaticSkin => Construct(0x53565b);
            public static FormLink<IBookGetter> xMASpellTomeBlueFlames => Construct(0x535662);
            public static FormLink<IBookGetter> xMAEasterEggJosephNote => Construct(0x5722c2);
            public static FormLink<IBookGetter> xMAMAGFocusLenseFireSpellTome => Construct(0x5ffff4);
            public static FormLink<IBookGetter> xMAMAGFocusLenseFrostSpellTome => Construct(0x5ffff6);
            public static FormLink<IBookGetter> xMAALTSpellTomeArcaneGenerator => Construct(0x605129);
            public static FormLink<IBookGetter> xMAALTSpellTomeRewind => Construct(0x60a231);
            public static FormLink<IBookGetter> xMAILLSpellTomePhantomSummonPhantomMudcrab => Construct(0x61e64e);
            public static FormLink<IBookGetter> xMAILLSpellTomeDelirium => Construct(0x641d68);
            public static FormLink<IBookGetter> xMAILLSpellTomeConfusion => Construct(0x641d72);
            public static FormLink<IBookGetter> xMAILLSpellTomeFeintStrength => Construct(0x641d75);
            public static FormLink<IBookGetter> xMAILLSpellTomeSilencingOrb => Construct(0x641d7e);
            public static FormLink<IBookGetter> xMAALTSpellTomeArtificialSun => Construct(0x68dce4);
            public static FormLink<IBookGetter> xMAALTSpellTomeSunburst => Construct(0x68dce5);
            public static FormLink<IBookGetter> xMABlankJournal0 => Construct(0x70c63d);
            public static FormLink<IBookGetter> xMABlankJournal1 => Construct(0x70c63e);
            public static FormLink<IBookGetter> xMACONSpellTomeSevenSouls => Construct(0x72ac4f);
            public static FormLink<IBookGetter> xMAEasterEggPatreonNote => Construct(0x753495);
            public static FormLink<IBookGetter> xMACONSpellTomeMarkOfDecay => Construct(0x251daa);
            public static FormLink<IBookGetter> xMACONSpellTomeBoundLongbow => Construct(0x251dab);
            public static FormLink<IBookGetter> xMACONSpellTomeVeinOfRagingUndead => Construct(0x251dac);
            public static FormLink<IBookGetter> xMACONSpellTomeConjureUnboundStormAtronach => Construct(0x251dad);
            public static FormLink<IBookGetter> xMAILLSpellTomeFear => Construct(0x251dae);
            public static FormLink<IBookGetter> xMAALTSpellTomePolymorph => Construct(0xca754e);
            public static FormLink<IBookGetter> xMAILLSpellTomeScapegoat => Construct(0x251daf);
            public static FormLink<IBookGetter> xMAILLSpellTomeFeintSwap => Construct(0x251db0);
            public static FormLink<IBookGetter> xMADESSpellTomeCriticalCasting => Construct(0xcac654);
            public static FormLink<IBookGetter> xMAILLSpellTomeStumble => Construct(0x251db1);
            public static FormLink<IBookGetter> xMAILLSpellTomeMindFabric => Construct(0x251db2);
            public static FormLink<IBookGetter> xMAILLSpellTomePhantomSpider => Construct(0x251db3);
            public static FormLink<IBookGetter> xMARESSpellTomeKingsbane => Construct(0x251dbd);
            public static FormLink<IBookGetter> xMARESSpellTomeCurePoison => Construct(0x251dbc);
            public static FormLink<IBookGetter> xMARESSpellTomeShieldWard => Construct(0x251dbb);
            public static FormLink<IBookGetter> xMARESSpellTomeCurseOfInfestation => Construct(0x251dba);
            public static FormLink<IBookGetter> xMARESSpellTomeAuraCryomancersSight => Construct(0x251dbe);
            public static FormLink<IBookGetter> xMAILLSpellTomeDarkness => Construct(0x251db4);
            public static FormLink<IBookGetter> xMAILLSpellTomeFeintImpact => Construct(0x251db5);
            public static FormLink<IBookGetter> xMAILLSpellTomeConcealingCloak => Construct(0x251db6);
            public static FormLink<IBookGetter> xMAILLSpellTomeFeintTrap => Construct(0x251db7);
            public static FormLink<IBookGetter> xMARESSpellTomeAuraChastise => Construct(0x251db8);
            public static FormLink<IBookGetter> xMARESSpellTomeAuraArmoredAscenion => Construct(0x251db9);
            public static FormLink<IBookGetter> xMARESSpellTomeAuraGrandBlaze => Construct(0x251dbf);
            public static FormLink<IBookGetter> xMARESSpellTomeAuraUpcomingTempest => Construct(0x251dc0);
            public static FormLink<IBookGetter> xMARESSpellTomeLegionfall => Construct(0x251dc6);
            public static FormLink<IBookGetter> xMARESSpellTomeCurseOfRoots => Construct(0x251dc5);
            public static FormLink<IBookGetter> xMARESSpellTomeThornswreath => Construct(0x251dc4);
            public static FormLink<IBookGetter> xMARESSpellTomePurgatory => Construct(0x251dc3);
            public static FormLink<IBookGetter> xMAALTSpellTomeEnhanceWeaponLeechingSpikes => Construct(0x251dc7);
            public static FormLink<IBookGetter> xMARESSpellTomeCurseOfBloodMagic => Construct(0x251dc1);
            public static FormLink<IBookGetter> xMADESSpellTomeWildfire => Construct(0xd3f395);
            public static FormLink<IBookGetter> xMADESSpellTomeCombustion => Construct(0xd3f39a);
            public static FormLink<IBookGetter> xMARESSpellTomeBrainmeltSyndrome => Construct(0x251dc2);
            public static FormLink<IBookGetter> xMAALTSpellTomeWarp => Construct(0x251dc8);
            public static FormLink<IBookGetter> xMAALTSpellTomeWaterwalking => Construct(0x251dc9);
            public static FormLink<IBookGetter> xMAALTSpellTomeKineticPush => Construct(0x251dca);
            public static FormLink<IBookGetter> xMAALTSpellTomePhaseShift => Construct(0x251dcb);
            public static FormLink<IBookGetter> xMARESSpellTomePlagueOutbreak => Construct(0xd5d9a8);
            public static FormLink<IBookGetter> xMAALTSpellTomeEnhanceWeaponRustedBlade => Construct(0x251dcc);
            public static FormLink<IBookGetter> xMAALTSpellTomeWeakenGravity => Construct(0x251dcd);
            public static FormLink<IBookGetter> xMAALTSpellTomeTelekinesis => Construct(0x251dce);
            public static FormLink<IBookGetter> xMAALTSpellTomeWaterbreathing => Construct(0x251dcf);
            public static FormLink<IBookGetter> xMAILLSpellTomePastPerception => Construct(0xd6ccb6);
            public static FormLink<IBookGetter> xMAALTSpellTomeTransmuteMineralOre => Construct(0x251dd0);
            public static FormLink<IBookGetter> xMAALTSpellTomeFreedom => Construct(0x251dd5);
            public static FormLink<IBookGetter> xMAALTSpellTomeImprison => Construct(0x251dd4);
            public static FormLink<IBookGetter> xMAALTSpellTomeEnhanceWeaponSunlightBlade => Construct(0x251dd3);
            public static FormLink<IBookGetter> xMAALTSpellTomeEnhanceWeaponSpellEater => Construct(0x251dd2);
            public static FormLink<IBookGetter> xMAALTSpellTomeEnhanceWeaponExplosiveSaliva => Construct(0x251dd6);
            public static FormLink<IBookGetter> xMAALTSpellTomeCombatShift => Construct(0x251dd1);
            public static FormLink<IBookGetter> xMADESSpellTomeFieryTouch => Construct(0x251dd7);
        }
    }
}
