// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class CombatStyle
        {
            private static FormLink<ICombatStyleGetter> Construct(uint id) => new FormLink<ICombatStyleGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ICombatStyleGetter> xMAENCAnimateWeaponCS => Construct(0x136292);
            public static FormLink<ICombatStyleGetter> xMAILLCloakOfDespairCombatStyle => Construct(0x38e02c);
        }
    }
}
