// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class EffectShader
        {
            private static FormLink<IEffectShaderGetter> Construct(uint id) => new FormLink<IEffectShaderGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IEffectShaderGetter> xMARESAuraHitShader => Construct(0x29662);
            public static FormLink<IEffectShaderGetter> xMARESAuraArmoredAscensionShader => Construct(0x33890);
            public static FormLink<IEffectShaderGetter> xMARESAuraThornsEmbraceShader => Construct(0x33892);
            public static FormLink<IEffectShaderGetter> xMARESAuraAspectOfBrillianceShader0 => Construct(0x42bf5);
            public static FormLink<IEffectShaderGetter> xMARESAuraAspectOfBrillianceShader1 => Construct(0x42bf9);
            public static FormLink<IEffectShaderGetter> xMAALTSpellbinderShader => Construct(0x61292);
            public static FormLink<IEffectShaderGetter> xMAALTSpellbinderToggleShader => Construct(0x61298);
            public static FormLink<IEffectShaderGetter> xMASNEOilShader => Construct(0xa969b);
            public static FormLink<IEffectShaderGetter> xMADESStaticSkinEffectShader => Construct(0x303278);
            public static FormLink<IEffectShaderGetter> xMADESFrostFrostburnDCSpellEffectShader => Construct(0x526342);
            public static FormLink<IEffectShaderGetter> xMARESCurseOfStoneFX => Construct(0x1a2fa);
            public static FormLink<IEffectShaderGetter> xMARESAuraGrandBlazeShader => Construct(0x24548);
        }
    }
}
