// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Explosion
        {
            private static FormLink<IExplosionGetter> Construct(uint id) => new FormLink<IExplosionGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IExplosionGetter> xMACONSummonUnboundFlameAtronachExploion => Construct(0x1b9dfd);
            public static FormLink<IExplosionGetter> xMACONSummonUnboundFrostAtronachExploion => Construct(0x1b9dfe);
            public static FormLink<IExplosionGetter> xMACONSummonUnboundStormAtronachExploion => Construct(0x1b9dff);
            public static FormLink<IExplosionGetter> xMAALTInverseShiftExplosion => Construct(0x1d3340);
            public static FormLink<IExplosionGetter> xMAALTEnhanceWeaponExplosiveSalivaExplosion => Construct(0x1e775e);
            public static FormLink<IExplosionGetter> xMAILLPhantomComboFeintImpactSpellExplosion => Construct(0x1ec88a);
            public static FormLink<IExplosionGetter> xMADESFireRuneExplosion => Construct(0x21f348);
            public static FormLink<IExplosionGetter> xMADESFrostFrostRuneExplosion => Construct(0x21f349);
            public static FormLink<IExplosionGetter> xMADESShockLightningRuneExplosion => Construct(0x21f34e);
            public static FormLink<IExplosionGetter> xMARESLegionfallExplosion => Construct(0x2754fe);
            public static FormLink<IExplosionGetter> xMAILLInfluenceFrenzyRuneProjectileExplosion => Construct(0x2e4c4c);
            public static FormLink<IExplosionGetter> xMADEXInventor2OilContainerExplosion => Construct(0x3be996);
            public static FormLink<IExplosionGetter> xMASMIPlaceTrapProjectileExplosion => Construct(0x3dcfff);
            public static FormLink<IExplosionGetter> xMAWAYWildCompanion0Explosion => Construct(0x3e7218);
            public static FormLink<IExplosionGetter> xMAWAYWildCompanion1Explosion => Construct(0x3e7219);
            public static FormLink<IExplosionGetter> xMAALCFuseExplosion => Construct(0x40587e);
            public static FormLink<IExplosionGetter> xMAALCAdvancedExplosivesMissileExplosion => Construct(0x40587f);
            public static FormLink<IExplosionGetter> xMARANAdvancedMissilecraft1BarbedExplosion => Construct(0x405881);
            public static FormLink<IExplosionGetter> xMAALCElementalBurstExplosionShock => Construct(0x405885);
            public static FormLink<IExplosionGetter> xMAALCElementalBurstExplosionFrost => Construct(0x405886);
            public static FormLink<IExplosionGetter> xMAALCElementalBurstExplosionFire => Construct(0x405887);
            public static FormLink<IExplosionGetter> xMAENCGreatInfusionToggleExplosion => Construct(0x419cb0);
            public static FormLink<IExplosionGetter> xMACONSummonSkeletonExplosion => Construct(0x4495f9);
            public static FormLink<IExplosionGetter> xMACONSummonSkeletonOverlordExplosion => Construct(0x4495fb);
            public static FormLink<IExplosionGetter> xMACONHarvestExplosion => Construct(0x45da32);
            public static FormLink<IExplosionGetter> xMARESCurseOfInfestationExplosion => Construct(0x462b35);
            public static FormLink<IExplosionGetter> xMAALTPhaseShiftExplosion => Construct(0x49a659);
            public static FormLink<IExplosionGetter> xMADESFireHeavyFireballEffectExplosion => Construct(0x507cfe);
            public static FormLink<IExplosionGetter> xMADESShockGreatThundercallSpell0EffectExplosion => Construct(0x507d07);
            public static FormLink<IExplosionGetter> xMADESShockGreatThundercallSpell1EffectExplosion => Construct(0x507d0a);
            public static FormLink<IExplosionGetter> xMADESShockGreatThundercallSpell2EffectExplosion => Construct(0x507d0b);
            public static FormLink<IExplosionGetter> xMADESShockGreatThundercallSpell3EffectExplosion => Construct(0x507d0c);
            public static FormLink<IExplosionGetter> xMADESShockGreatThundercallSpell4EffectExplosion => Construct(0x507d0d);
            public static FormLink<IExplosionGetter> xMADESShockGreatThundercallSpell5EffectExplosion => Construct(0x507d0e);
            public static FormLink<IExplosionGetter> xMAALTSpellPrismEffectExplosion => Construct(0x67e9dc);
            public static FormLink<IExplosionGetter> xMADESFireCombustionEffect1Explosion => Construct(0xd3f397);
            public static FormLink<IExplosionGetter> xMADESMixedHellfireCageExplosionSpawn => Construct(0x734e57);
            public static FormLink<IExplosionGetter> xMADESMixedHellfireCageExplosionShockSpawn => Construct(0x734e58);
            public static FormLink<IExplosionGetter> xMADESMixedHellfireCageExplosionDespawn => Construct(0x734e59);
            public static FormLink<IExplosionGetter> xMADESConflagrationExplosion => Construct(0x73f05e);
            public static FormLink<IExplosionGetter> xMAALCPoisonBurstAmmoPoisonExplosion => Construct(0x73f060);
            public static FormLink<IExplosionGetter> xMADESConflagrateExplosion => Construct(0xaa02);
            public static FormLink<IExplosionGetter> xMARESCurseOfStoneExplosion => Construct(0x1a304);
            public static FormLink<IExplosionGetter> xMARESPurgatoryExplosion => Construct(0x3dace);
            public static FormLink<IExplosionGetter> xMASNERopeArrowExplosion => Construct(0x4e3a3);
            public static FormLink<IExplosionGetter> xMAALCAdhesiveExplosivesExplosion => Construct(0x50de4);
            public static FormLink<IExplosionGetter> xMAALTCombatShiftExplosion => Construct(0x51f2c);
            public static FormLink<IExplosionGetter> xMAALTKineticWaveExplosion => Construct(0x51f35);
            public static FormLink<IExplosionGetter> xMAALTKineticShiftTeleportExplosion => Construct(0x5704a);
            public static FormLink<IExplosionGetter> xMAALTKineticShiftExplosion => Construct(0x5704b);
            public static FormLink<IExplosionGetter> xMASNEMeasureDistanceExplosion => Construct(0x59000);
            public static FormLink<IExplosionGetter> xMASNEWaterArrowExplosion => Construct(0x6e694);
            public static FormLink<IExplosionGetter> xMAALTArtificialSunExplosion => Construct(0x70607);
            public static FormLink<IExplosionGetter> xMAALTArtificialSunCreateSunExplosion => Construct(0x7a866);
            public static FormLink<IExplosionGetter> xMAALTSunburstRemainsExplosion => Construct(0x7a868);
            public static FormLink<IExplosionGetter> xMASNEFireArrowExplosion => Construct(0x8b75c);
            public static FormLink<IExplosionGetter> xMASNENoisemakerArrowExplosion => Construct(0x8d24a);
            public static FormLink<IExplosionGetter> xMASNEOilArrowExplosion => Construct(0x91dac);
            public static FormLink<IExplosionGetter> xMADESFrostFieldExplosion => Construct(0x98ef8);
            public static FormLink<IExplosionGetter> xMAALTSunburstExplosion => Construct(0x98efe);
            public static FormLink<IExplosionGetter> xMASNEFindGroundOilExplosion => Construct(0x9da24);
            public static FormLink<IExplosionGetter> xMASNEFindGroundOilExplosionMaster => Construct(0x9df89);
            public static FormLink<IExplosionGetter> xMASNETrapOilExplosion01 => Construct(0x9df8c);
            public static FormLink<IExplosionGetter> xMASNETrapOilExplosionMaster => Construct(0x9efb5);
            public static FormLink<IExplosionGetter> xMASNETrapOilExplosionInitial => Construct(0x9f518);
            public static FormLink<IExplosionGetter> xMASMIAnimunculiSpawnExplosion => Construct(0xa82a4);
            public static FormLink<IExplosionGetter> xMACONSevenSoulsExplosion => Construct(0xc1847);
            public static FormLink<IExplosionGetter> xMACONMarkOfPowerExplosion => Construct(0xc184c);
            public static FormLink<IExplosionGetter> xMADESMixedHeavenlapseShockSpellExplosion => Construct(0xea28e);
            public static FormLink<IExplosionGetter> xMADESMixedHeavenlapseFrostSpellExplosion => Construct(0xea28f);
            public static FormLink<IExplosionGetter> xMAALCPoisonArmorHitExplosion => Construct(0x108900);
            public static FormLink<IExplosionGetter> xMARESCurseOfRootsExplosion => Construct(0x135510);
            public static FormLink<IExplosionGetter> xMADESSiegeModeCastExplosion => Construct(0x1404ad);
            public static FormLink<IExplosionGetter> xMACONGatesOfOblivionExplosion => Construct(0x18223f);
            public static FormLink<IExplosionGetter> xMACONGatesOfOblivionSpawnExplosion => Construct(0x182244);
            public static FormLink<IExplosionGetter> xMADESAbsoluteZeroSpellExplosion => Construct(0x1a08ac);
            public static FormLink<IExplosionGetter> xMAALCTrapPoisonExplosion => Construct(0x1a23ff);
            public static FormLink<IExplosionGetter> xMAALCAdvancedExplosivesTrapExplosion => Construct(0x1a2409);
            public static FormLink<IExplosionGetter> xMAALCElementalBurstTrapBearFireExplosion => Construct(0x1a2419);
            public static FormLink<IExplosionGetter> xMAALCElementalBurstTrapBearFrostExplosion => Construct(0x1a241b);
            public static FormLink<IExplosionGetter> xMAALCElementalBurstTrapBearShockExplosion => Construct(0x1a241c);
            public static FormLink<IExplosionGetter> xMAALCPoisonBurstParalysisExplosion => Construct(0x1a4bc4);
        }
    }
}
