// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Faction
        {
            private static FormLink<IFactionGetter> Construct(uint id) => new FormLink<IFactionGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFactionGetter> xMACONDeconstructedFaction => Construct(0x705d8);
            public static FormLink<IFactionGetter> xMAILLVesselFaction => Construct(0x98f17);
            public static FormLink<IFactionGetter> xMASMIAnimunculiFaction => Construct(0xa828a);
            public static FormLink<IFactionGetter> xMASNEHorstarVendorFactionDawnguard => Construct(0xabc5b);
            public static FormLink<IFactionGetter> xMAILLPhantomFaction => Construct(0xc835c);
            public static FormLink<IFactionGetter> xMACONUndeadFollowerFaction => Construct(0x121e4f);
            public static FormLink<IFactionGetter> xMASNEUnconsciousFaction => Construct(0x17b72);
            public static FormLink<IFactionGetter> xMASNEHorstarVendorFaction => Construct(0x62cd7);
            public static FormLink<IFactionGetter> xMASNEHorstarOwnerFaction => Construct(0x63f91);
        }
    }
}
