// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class FormList
        {
            private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFormListGetter> xMAFormListSpellIllusionExpert => Construct(0x100ae);
            public static FormLink<IFormListGetter> xMAFormListSpellIllusionMaster => Construct(0x100af);
            public static FormLink<IFormListGetter> xMAFormListSpellDestructionNovice => Construct(0x100b0);
            public static FormLink<IFormListGetter> xMAFormListSpellDestructionApprentice => Construct(0x100b1);
            public static FormLink<IFormListGetter> xMAFormListSpellDestructionAdept => Construct(0x100b2);
            public static FormLink<IFormListGetter> xMAFormListSpellDestructionExpert => Construct(0x100b3);
            public static FormLink<IFormListGetter> xMAFormListSpellDestructionMaster => Construct(0x100b4);
            public static FormLink<IFormListGetter> xMAFormListSpellAlterationNovice => Construct(0x100b5);
            public static FormLink<IFormListGetter> xMAFormListSpellAlterationApprentice => Construct(0x100b6);
            public static FormLink<IFormListGetter> xMAFormListSpellAlterationAdept => Construct(0x100b7);
            public static FormLink<IFormListGetter> xMAFormListSpellAlterationExpert => Construct(0x100b8);
            public static FormLink<IFormListGetter> xMAFormListSpellAlterationMaster => Construct(0x100b9);
            public static FormLink<IFormListGetter> xMAFormListShoutsDragon => Construct(0x1f40b);
            public static FormLink<IFormListGetter> xMAFormListPerkGrantedSpells => Construct(0x2452b);
            public static FormLink<IFormListGetter> xMAFormListAllSpells => Construct(0x24540);
            public static FormLink<IFormListGetter> xMAFormListSpellAuraAbilities => Construct(0x24541);
            public static FormLink<IFormListGetter> xMAFormListSpellAuraDebuffs => Construct(0x29663);
            public static FormLink<IFormListGetter> xMAFormListSpellbinderExclusions => Construct(0x6129b);
            public static FormLink<IFormListGetter> xMAALTSacrificialCastingExclusionSpells => Construct(0x6b4a4);
            public static FormLink<IFormListGetter> xMACONUndeadList => Construct(0x705cd);
            public static FormLink<IFormListGetter> xMASNECandlesONFormList => Construct(0x70d6f);
            public static FormLink<IFormListGetter> xMASNEFiresONFormList => Construct(0x70d71);
            public static FormLink<IFormListGetter> xMASNEFiresOFFFormList => Construct(0x70d72);
            public static FormLink<IFormListGetter> xMASNETorchesONFormList => Construct(0x70d73);
            public static FormLink<IFormListGetter> xMASNETorchesOFFFormList => Construct(0x70d74);
            public static FormLink<IFormListGetter> xMASNEFireLightsFormList => Construct(0x74e51);
            public static FormLink<IFormListGetter> xMASMIDwarvenAnimunculiContainers => Construct(0xa82a3);
            public static FormLink<IFormListGetter> xMASNECandlesOFFFormList => Construct(0x7232b);
            public static FormLink<IFormListGetter> xMADEXUtilityBeltFormList => Construct(0x377aa7);
            public static FormLink<IFormListGetter> xMAILLCloakOfDespairList => Construct(0x38e02e);
            public static FormLink<IFormListGetter> xMASNEEnchantmentHelmets => Construct(0xaac34);
            public static FormLink<IFormListGetter> xMACONFormListMarkOfPowerSpells => Construct(0xc1850);
            public static FormLink<IFormListGetter> xMADESRagingInfernoFormList => Construct(0x168d14);
            public static FormLink<IFormListGetter> xMAFormListPerkFactions => Construct(0x17802e);
            public static FormLink<IFormListGetter> xMADESFormListAbsoluteZero => Construct(0x1a08ab);
            public static FormLink<IFormListGetter> xMACONVeinPerks => Construct(0x205e03);
            public static FormLink<IFormListGetter> xMAILLFormListInfluenceBlocker => Construct(0x2fe16a);
            public static FormLink<IFormListGetter> xMADESFormListStaticSkin => Construct(0x30327b);
            public static FormLink<IFormListGetter> xMAFormListPlayerShoutSpells => Construct(0x3125b6);
            public static FormLink<IFormListGetter> xMADEXUnburdenedFormList => Construct(0x363643);
            public static FormLink<IFormListGetter> xMAFormListPerksWayfarer => Construct(0x39b204);
            public static FormLink<IFormListGetter> xMAFormListPerksProdigy => Construct(0x3b9889);
            public static FormLink<IFormListGetter> xMAFormListPerksBlock => Construct(0x39b203);
            public static FormLink<IFormListGetter> xMAFormListSpellsIllusion => Construct(0x5e19cc);
            public static FormLink<IFormListGetter> xMAFormListSpellsRestoration => Construct(0x5e19cd);
            public static FormLink<IFormListGetter> xMAENCGreatInfusionEnchWeaponRestrictions => Construct(0x40fa95);
            public static FormLink<IFormListGetter> xMAENCGreatInfusionEnchArmorRestrictions => Construct(0x40fa96);
            public static FormLink<IFormListGetter> xMAENCArcaneArcheryAbilityList => Construct(0x4351c6);
            public static FormLink<IFormListGetter> xMANewWeapons => Construct(0x44c732);
            public static FormLink<IFormListGetter> DELxMAFormListSpellsAll => Construct(0x44c733);
            public static FormLink<IFormListGetter> xMAEasterEggFormList => Construct(0x5722c3);
            public static FormLink<IFormListGetter> xMAFormListSpellsAlteration => Construct(0x5e19c6);
            public static FormLink<IFormListGetter> xMAFormListSpellsConjuration => Construct(0x5e19ca);
            public static FormLink<IFormListGetter> xMAFormListSpellsDestruction => Construct(0x5e19cb);
            public static FormLink<IFormListGetter> xMAALTStudiesMasterAlterationFormList => Construct(0x5f5dde);
            public static FormLink<IFormListGetter> xMAALTStudiesAdeptDestructionFormList => Construct(0x5f5de0);
            public static FormLink<IFormListGetter> xMASPELeadershipEliteTankFormList => Construct(0x75348f);
            public static FormLink<IFormListGetter> xMASPELeadershipEliteMageFormList => Construct(0x753491);
            public static FormLink<IFormListGetter> xMAFormListConcentrationSpells => Construct(0x5faee9);
            public static FormLink<IFormListGetter> xMADisparityList => Construct(0x734e5a);
            public static FormLink<IFormListGetter> xMASPELeadershipEliteArcherFormList => Construct(0x753492);
            public static FormLink<IFormListGetter> xMADEXDontStealFormList => Construct(0x753496);
            public static FormLink<IFormListGetter> xMAFormListPerksConjuration => Construct(0x10080);
            public static FormLink<IFormListGetter> xMAFormListPerksEnchanting => Construct(0x10081);
            public static FormLink<IFormListGetter> PerkusMaximus_MasterForms => Construct(0xc74b39);
            public static FormLink<IFormListGetter> xMAFormListPerksAll => Construct(0x1007e);
            public static FormLink<IFormListGetter> xMAFormListPerksRestoration => Construct(0x1007f);
            public static FormLink<IFormListGetter> xMAFormListPerksDestruction => Construct(0x10082);
            public static FormLink<IFormListGetter> xMAFormListPerksIllusion => Construct(0x10083);
            public static FormLink<IFormListGetter> xMAFormListPerksSpeechcraft => Construct(0x10088);
            public static FormLink<IFormListGetter> xMAFormListPerksSmithing => Construct(0x1008a);
            public static FormLink<IFormListGetter> xMAFormListPerksAlchemy => Construct(0x10085);
            public static FormLink<IFormListGetter> xMAFormListPerksLightArmor => Construct(0x10086);
            public static FormLink<IFormListGetter> xMAFormListPerksAlteration => Construct(0x10084);
            public static FormLink<IFormListGetter> xMAFormListPerksSneak => Construct(0x10087);
            public static FormLink<IFormListGetter> xMAFormListSpellRestorationExpert => Construct(0x100a4);
            public static FormLink<IFormListGetter> xMAFormListPerksRangedWeaponry => Construct(0x1008e);
            public static FormLink<IFormListGetter> xMAFormListPerksLightWeaponry => Construct(0x1008b);
            public static FormLink<IFormListGetter> xMAFormListPerksDexterity => Construct(0x10089);
            public static FormLink<IFormListGetter> xMAFormListPerksHeavyWeaponry => Construct(0x1008c);
            public static FormLink<IFormListGetter> xMAFormListPerksHeavyArmor => Construct(0x1008d);
            public static FormLink<IFormListGetter> xMAFormListSpellRestorationAdept => Construct(0x100a3);
            public static FormLink<IFormListGetter> xMAFormListSpellRestorationNovice => Construct(0x100a1);
            public static FormLink<IFormListGetter> xMAFormListSpellRestorationApprentice => Construct(0x100a2);
            public static FormLink<IFormListGetter> xMAFormListSpellConjurationMaster => Construct(0x100aa);
            public static FormLink<IFormListGetter> xMAFormListSpellIllusionNovice => Construct(0x100ab);
            public static FormLink<IFormListGetter> xMAFormListSpellRestorationMaster => Construct(0x100a5);
            public static FormLink<IFormListGetter> xMAFormListSpellConjurationNovice => Construct(0x100a6);
            public static FormLink<IFormListGetter> xMAFormListPerksFocus => Construct(0xd903ca);
            public static FormLink<IFormListGetter> xMAFormListPerksMastery => Construct(0xd903c9);
            public static FormLink<IFormListGetter> xMAFormListSpellConjurationApprentice => Construct(0x100a7);
            public static FormLink<IFormListGetter> xMAFormListSpellConjurationAdept => Construct(0x100a8);
            public static FormLink<IFormListGetter> xMAFormListSpellConjurationExpert => Construct(0x100a9);
            public static FormLink<IFormListGetter> xMAFormListSpellIllusionApprentice => Construct(0x100ac);
            public static FormLink<IFormListGetter> xMAFormListSpellIllusionAdept => Construct(0x100ad);
        }
    }
}
