// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Furniture
        {
            private static FormLink<IFurnitureGetter> Construct(uint id) => new FormLink<IFurnitureGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFurnitureGetter> xMAENCInscribeMarker => Construct(0x28394a);
            public static FormLink<IFurnitureGetter> xMAALCFieldAlchemyMarker => Construct(0x28394c);
            public static FormLink<IFurnitureGetter> xMAWorkbenchEnchantingHidden => Construct(0xd30078);
        }
    }
}
