// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Global
        {
            private static FormLink<IGlobalGetter> Construct(uint id) => new FormLink<IGlobalGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IGlobalGetter> xMASPELeadershipMookMax => Construct(0x183f);
            public static FormLink<IGlobalGetter> xMARESPlagueLegionfallCounter => Construct(0x1a2fc);
            public static FormLink<IGlobalGetter> xMAIsTimedBlocking => Construct(0x1f414);
            public static FormLink<IGlobalGetter> xMATimedBlockingTolerance => Construct(0x1f416);
            public static FormLink<IGlobalGetter> xMAALTWeakenGravityActiveGlobal => Construct(0x51f37);
            public static FormLink<IGlobalGetter> xMAFocusPerksChosen => Construct(0x57050);
            public static FormLink<IGlobalGetter> xMAFocusPerksMax => Construct(0x57051);
            public static FormLink<IGlobalGetter> xMASNESpawnRope => Construct(0x57a70);
            public static FormLink<IGlobalGetter> xMASNEFloorZ => Construct(0x59002);
            public static FormLink<IGlobalGetter> xMASNEUseMenus => Construct(0x64fc6);
            public static FormLink<IGlobalGetter> xMASNEAllowEssentialKill => Construct(0x695c9);
            public static FormLink<IGlobalGetter> xMACONBoneMasteryChanceBoneBack => Construct(0x705e0);
            public static FormLink<IGlobalGetter> xMACONBoneMasteryDestroyedSkeletons => Construct(0x705e1);
            public static FormLink<IGlobalGetter> xMACONChanceBone => Construct(0x705e2);
            public static FormLink<IGlobalGetter> xMACONChanceFlesh => Construct(0x705e3);
            public static FormLink<IGlobalGetter> xMACONChanceHeart => Construct(0x705e4);
            public static FormLink<IGlobalGetter> xMASkeletonCountMax => Construct(0x705e9);
            public static FormLink<IGlobalGetter> xMAALTArtificialSunUp => Construct(0x70606);
            public static FormLink<IGlobalGetter> xMAWAYExperienceGainBase => Construct(0x8e225);
            public static FormLink<IGlobalGetter> xMASNEPlayOilEffects => Construct(0x9e4f0);
            public static FormLink<IGlobalGetter> xMAALCTrapMaxPoisonCount => Construct(0xfe6d6);
            public static FormLink<IGlobalGetter> xMADEXLockpickingExpBase => Construct(0x117c27);
            public static FormLink<IGlobalGetter> xMAILLPhantomCountCurrent => Construct(0x12c05c);
            public static FormLink<IGlobalGetter> xMAILLPhantomCountMax => Construct(0x12c05d);
            public static FormLink<IGlobalGetter> xMACONGateToOblivionOpen => Construct(0x1b4cf7);
            public static FormLink<IGlobalGetter> xMAENCScrollBaseExp => Construct(0x310c01);
            public static FormLink<IGlobalGetter> xMAIsPerMaWarriorRunning => Construct(0x3176c9);
            public static FormLink<IGlobalGetter> xMAIsPerMaMageRunning => Construct(0x3176ca);
            public static FormLink<IGlobalGetter> xMAIsPerMaThiefRunning => Construct(0x3176cb);
            public static FormLink<IGlobalGetter> xMAWARArmorPassiveSkillBase => Construct(0x36d87b);
            public static FormLink<IGlobalGetter> xMARANArrowhailHitCountCurrent => Construct(0x3aa529);
            public static FormLink<IGlobalGetter> xMARANArrowhailHitCountMax => Construct(0x3aa52a);
            public static FormLink<IGlobalGetter> xMASPELeadershipArcherMax => Construct(0x3af65f);
            public static FormLink<IGlobalGetter> xMASPELeadershipMageMax => Construct(0x3af660);
            public static FormLink<IGlobalGetter> xMASPELeadershipMookCurrent => Construct(0x3af661);
            public static FormLink<IGlobalGetter> xMASPELeadershipTankMax => Construct(0x3af662);
            public static FormLink<IGlobalGetter> xMAProdigyPerksChosen => Construct(0x3b987d);
            public static FormLink<IGlobalGetter> xMAProdigyPerksMax => Construct(0x3b987e);
            public static FormLink<IGlobalGetter> xMAMasteryPerksChosen => Construct(0x3b987f);
            public static FormLink<IGlobalGetter> xMAMasteryPerksMax => Construct(0x3b9880);
            public static FormLink<IGlobalGetter> xMAHEAMasteryUnyieldingTowerToggleCurrent => Construct(0x3c8bc2);
            public static FormLink<IGlobalGetter> xMAHEAMasteryUnyieldingTowerToggleMax => Construct(0x3c8bc3);
            public static FormLink<IGlobalGetter> xMARANMasterySkillshotToggleCurrent => Construct(0x3d2ddb);
            public static FormLink<IGlobalGetter> xMARANMasterySkillshotToggleMax => Construct(0x3d2ddc);
            public static FormLink<IGlobalGetter> xMALIARecklessAbandonToggleMax => Construct(0x3d7ee9);
            public static FormLink<IGlobalGetter> xMALIARecklessAbandonToggleCurrent => Construct(0x3d7eec);
            public static FormLink<IGlobalGetter> xMAWAYWildCompanionUseMax => Construct(0x3e7216);
            public static FormLink<IGlobalGetter> xMAWAYWildCompanionUseCurr => Construct(0x3e7217);
            public static FormLink<IGlobalGetter> xMAWAYShapeshifterCountCurrent => Construct(0x3f656e);
            public static FormLink<IGlobalGetter> xMAWAYShapeshifterCountMax => Construct(0x3f6572);
            public static FormLink<IGlobalGetter> xMATHIShoutExpBase => Construct(0x44251b);
            public static FormLink<IGlobalGetter> xMACONLordOfBonesDestroyedSkeletons => Construct(0x4495f3);
            public static FormLink<IGlobalGetter> xMAWAYWildCompanionAnimalCurr => Construct(0x4cb0a0);
            public static FormLink<IGlobalGetter> xMAALCTinkererIsTaken => Construct(0x744165);
            public static FormLink<IGlobalGetter> xMAALTNoviceIsTaken => Construct(0x744167);
            public static FormLink<IGlobalGetter> xMAALTApprenticeIsTaken => Construct(0x744168);
            public static FormLink<IGlobalGetter> xMAALTAdeptIsTaken => Construct(0x744169);
            public static FormLink<IGlobalGetter> xMAALTExpertIsTaken => Construct(0x74416a);
            public static FormLink<IGlobalGetter> xMACONNoviceIsTaken => Construct(0x74416b);
            public static FormLink<IGlobalGetter> xMACONApprenticeIsTaken => Construct(0x74416c);
            public static FormLink<IGlobalGetter> xMACONAdeptIsTaken => Construct(0x74416d);
            public static FormLink<IGlobalGetter> xMACONExpertIsTaken => Construct(0x74416e);
            public static FormLink<IGlobalGetter> xMACONMasterIsTaken => Construct(0x74416f);
            public static FormLink<IGlobalGetter> xMADESNoviceIsTaken => Construct(0x744170);
            public static FormLink<IGlobalGetter> xMADESApprenticeIsTaken => Construct(0x744171);
            public static FormLink<IGlobalGetter> xMADESAdeptIsTaken => Construct(0x744172);
            public static FormLink<IGlobalGetter> xMADESExpertIsTaken => Construct(0x744173);
            public static FormLink<IGlobalGetter> xMADESMasterIsTaken => Construct(0x744174);
            public static FormLink<IGlobalGetter> xMAILLNoviceIsTaken => Construct(0x744175);
            public static FormLink<IGlobalGetter> xMAILLApprenticeIsTaken => Construct(0x744176);
            public static FormLink<IGlobalGetter> xMAILLAdeptIsTaken => Construct(0x744177);
            public static FormLink<IGlobalGetter> xMAILLExpertIsTaken => Construct(0x744178);
            public static FormLink<IGlobalGetter> xMAILLMasterIsTaken => Construct(0x744179);
            public static FormLink<IGlobalGetter> xMAILLHallucinatingEchoesIsTaken => Construct(0x74417a);
            public static FormLink<IGlobalGetter> xMALIARecklessAbandonIsTaken => Construct(0x74417b);
            public static FormLink<IGlobalGetter> xMALIAWindWalkerIsTaken => Construct(0x74417c);
            public static FormLink<IGlobalGetter> xMARESNoviceIsTaken => Construct(0x74417d);
            public static FormLink<IGlobalGetter> xMARESApprenticeIsTaken => Construct(0x74417e);
            public static FormLink<IGlobalGetter> xMARESAdeptIsTaken => Construct(0x74417f);
            public static FormLink<IGlobalGetter> xMARESExpertIsTaken => Construct(0x744180);
            public static FormLink<IGlobalGetter> xMARESMasterIsTaken => Construct(0x744181);
            public static FormLink<IGlobalGetter> xMASMIwarforgedIsTaken => Construct(0x744182);
            public static FormLink<IGlobalGetter> xMASNESneakScriptIsTaken => Construct(0x744183);
            public static FormLink<IGlobalGetter> xMASNEInfiltratorIsTaken => Construct(0x744184);
            public static FormLink<IGlobalGetter> xMASPEDiplomatIsTaken => Construct(0x744185);
            public static FormLink<IGlobalGetter> xMASPEEloquenceIsTaken => Construct(0x744186);
            public static FormLink<IGlobalGetter> xMAWAYBeastmasterIsTaken => Construct(0x744187);
            public static FormLink<IGlobalGetter> xMAWAYShapeshifterIsTaken => Construct(0x744188);
            public static FormLink<IGlobalGetter> xMAALTMasterIsTaken => Construct(0x744189);
            public static FormLink<IGlobalGetter> xMASPELeadershipTankCurrent => Construct(0xd65);
            public static FormLink<IGlobalGetter> xMASPELeadershipArcherCurrent => Construct(0xd66);
            public static FormLink<IGlobalGetter> xMASPELeadershipMageCurrent => Construct(0xd67);
        }
    }
}
