// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Hazard
        {
            private static FormLink<IHazardGetter> Construct(uint id) => new FormLink<IHazardGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IHazardGetter> xMAALCFuseExplosionHazard => Construct(0x4c0e9a);
            public static FormLink<IHazardGetter> ORD_Des_Conflagration_Hazard => Construct(0x2846a);
            public static FormLink<IHazardGetter> xMADESFrostBlizzardHazard => Construct(0x8ecdf);
        }
    }
}
