// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class ImageSpaceAdapter
        {
            private static FormLink<IImageSpaceAdapterGetter> Construct(uint id) => new FormLink<IImageSpaceAdapterGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IImageSpaceAdapterGetter> xMAALTArtificialSunCreateSunExplosionImod => Construct(0x7a867);
            public static FormLink<IImageSpaceAdapterGetter> xMACONSevenSoulsIMOD => Construct(0xc1846);
        }
    }
}
