// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Ingestible
        {
            private static FormLink<IIngestibleGetter> Construct(uint id) => new FormLink<IIngestibleGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IIngestibleGetter> xMAALCElementalBurstBearTrapShockPotion => Construct(0x1088e1);
            public static FormLink<IIngestibleGetter> xMAPotionOfUnwoundFates => Construct(0x3f656c);
            public static FormLink<IIngestibleGetter> xMAALCPoisonBurstSpikesPoisonPotion => Construct(0x1c276b);
            public static FormLink<IIngestibleGetter> xMAALCElementalBurstBearTrapFirePotion => Construct(0x1088de);
            public static FormLink<IIngestibleGetter> xMAALCElementalBurstBearTrapFrostPotion => Construct(0x1088df);
            public static FormLink<IIngestibleGetter> xMAALCPoisonBurstBearTrapPoisonPotion => Construct(0x1a2406);
            public static FormLink<IIngestibleGetter> xMAALCPoisonBurstChillPaste => Construct(0x3c3aa4);
            public static FormLink<IIngestibleGetter> xMAWAYCamouflagePotion => Construct(0x354308);
            public static FormLink<IIngestibleGetter> xMAALCPoisonBurstThunderPaste => Construct(0x3c3a9f);
            public static FormLink<IIngestibleGetter> xMAALCPoisonBurstBearTrapParalysisPotion => Construct(0x1a4bcc);
            public static FormLink<IIngestibleGetter> xMAALCPoisonBurstFlamePaste => Construct(0x3c3aa2);
            public static FormLink<IIngestibleGetter> xMAPotionOfGreatPotential => Construct(0x3f6570);
            public static FormLink<IIngestibleGetter> xMAALCAdhesiveExplosivesPoison => Construct(0x50de5);
        }
    }
}
