// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Ingredient
        {
            private static FormLink<IIngredientGetter> Construct(uint id) => new FormLink<IIngredientGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IIngredientGetter> xMAALCDaedraSkin => Construct(0x6d9c1c);
            public static FormLink<IIngredientGetter> xMACONElvenFlesh => Construct(0x35c92);
            public static FormLink<IIngredientGetter> xMACONBeastHeart => Construct(0x705ce);
            public static FormLink<IIngredientGetter> xMACONElvenHeart => Construct(0x705d0);
            public static FormLink<IIngredientGetter> xMACONBeastFlesh => Construct(0x35c94);
        }
    }
}
