// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class LeveledNpc
        {
            private static FormLink<ILeveledNpcGetter> Construct(uint id) => new FormLink<ILeveledNpcGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledNpcGetter> xNPC_Leveled => Construct(0xaa37);
            public static FormLink<ILeveledNpcGetter> xNPC_Leveled_Male => Construct(0x7627a4);
            public static FormLink<ILeveledNpcGetter> xNPC_Leveled_Female => Construct(0x7627a5);
        }
    }
}
