// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class LeveledSpell
        {
            private static FormLink<ILeveledSpellGetter> Construct(uint id) => new FormLink<ILeveledSpellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub2Right => Construct(0xc7ed3d);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub5 => Construct(0x2e149);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub6 => Construct(0x2e14a);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub6 => Construct(0x2e152);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub3Right => Construct(0xc7ed3e);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub2 => Construct(0x2e14e);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub3 => Construct(0x2e14f);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub7 => Construct(0x2e14b);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsMAIN => Construct(0x2e14c);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub1 => Construct(0x2e14d);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub4 => Construct(0x2e150);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub5 => Construct(0x2e151);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsMAIN => Construct(0x2e144);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub1 => Construct(0x2e145);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledActorSpellsSub7 => Construct(0x2e153);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub2 => Construct(0x2e146);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub3 => Construct(0x2e147);
            public static FormLink<ILeveledSpellGetter> xNPC_LeveledUndeadSpellsSub4 => Construct(0x2e148);
        }
    }
}
