// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class LeveledItem
        {
            private static FormLink<ILeveledItemGetter> Construct(uint id) => new FormLink<ILeveledItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledItemGetter> xNPC_LeveledActorMageArmorSub1 => Construct(0x3325a);
            public static FormLink<ILeveledItemGetter> xNPC_LeveledActorMageArmorBoots => Construct(0x33261);
            public static FormLink<ILeveledItemGetter> xMACONSummonDremoraValkynazActorBowList => Construct(0x5f5dd9);
            public static FormLink<ILeveledItemGetter> xNPC_LeveledActorHeavyArmor => Construct(0x2e155);
            public static FormLink<ILeveledItemGetter> xNPC_LeveledActorLightArmor => Construct(0x2e156);
            public static FormLink<ILeveledItemGetter> xNPC_Leveled2HWeapon50 => Construct(0x2e142);
            public static FormLink<ILeveledItemGetter> xMASNEMasksLeveledItem => Construct(0x626c4);
            public static FormLink<ILeveledItemGetter> xNPC_LeveledActorMageArmorMAIN => Construct(0x33262);
        }
    }
}
