// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Light
        {
            private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightGetter> xMASNEThiefsToolboxLightsourceArrowLight => Construct(0x28ea50);
            public static FormLink<ILightGetter> xMADESImplosionFireballLight => Construct(0x84a77);
            public static FormLink<ILightGetter> xMAALTArtificialSunLight => Construct(0x7060c);
        }
    }
}
