// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Message
        {
            private static FormLink<IMessageGetter> Construct(uint id) => new FormLink<IMessageGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMessageGetter> xMACONNotEnoughIngredients => Construct(0x3620d);
            public static FormLink<IMessageGetter> xMAALTArcaneGeneratorReadyMessage => Construct(0x605128);
            public static FormLink<IMessageGetter> xMASpellOnCooldownMessage => Construct(0x68dce7);
            public static FormLink<IMessageGetter> xMACONFocusTheNecromageNotEnoughIngredients => Construct(0x72ac4b);
            public static FormLink<IMessageGetter> xMAALTKineticReadyMessage => Construct(0x51f38);
            public static FormLink<IMessageGetter> xMASNETouchOfCalamityMessage => Construct(0x38806);
            public static FormLink<IMessageGetter> xMAALTShiftReadyMessage => Construct(0x51f39);
            public static FormLink<IMessageGetter> xMAALTNoTwoSuns => Construct(0x70601);
            public static FormLink<IMessageGetter> xMACONRecurringNightmareNoCarcassMessage => Construct(0x705df);
            public static FormLink<IMessageGetter> xMAALTPolymorphMessage => Construct(0xca754f);
            public static FormLink<IMessageGetter> xMAALTSacrificialCastingOnColdown => Construct(0x6b4b2);
            public static FormLink<IMessageGetter> xMACONLevelTooLowToReanimate => Construct(0x7a856);
            public static FormLink<IMessageGetter> xMAALTImprisonAlreadyPrisonerMessage => Construct(0x5c15d);
            public static FormLink<IMessageGetter> xMAALTFreedomNoActorMessage => Construct(0x5c15c);
            public static FormLink<IMessageGetter> xMAALTKineticShiftReadyMessage => Construct(0x57049);
            public static FormLink<IMessageGetter> xMAALTNoSunUp => Construct(0x75749);
            public static FormLink<IMessageGetter> xMAALTImprisonDeadMessage => Construct(0x5c15b);
            public static FormLink<IMessageGetter> xMAALTKineticShiftOnCooldownMessage => Construct(0x57048);
            public static FormLink<IMessageGetter> xMAILLSummonPhantomAtMaximum => Construct(0x12c06c);
            public static FormLink<IMessageGetter> xMASNERecognizedMessage => Construct(0xd0d5f);
            public static FormLink<IMessageGetter> xMAALTSunDisappearing => Construct(0x98f02);
            public static FormLink<IMessageGetter> xMACONNoDeadSkeletonsMessage => Construct(0x121e50);
            public static FormLink<IMessageGetter> xMAALCNoTrapsToEnhanceBear => Construct(0xfe6d7);
            public static FormLink<IMessageGetter> xMAALCNoTrapsToEnhanceSpikes => Construct(0xfe6d8);
            public static FormLink<IMessageGetter> xMAALCPoisonArmorNoPhials => Construct(0x1088eb);
            public static FormLink<IMessageGetter> xMAALCPoisonArmorNoPhialsLeft => Construct(0x1088ec);
            public static FormLink<IMessageGetter> xMAENCAnimateWeaponNoWeaponMessage => Construct(0x136291);
            public static FormLink<IMessageGetter> xMAENCAnimateWeaponOnlyMeleeWeaponMessage => Construct(0x136294);
            public static FormLink<IMessageGetter> xMACONRemovedOldVeinMessage => Construct(0x205e06);
            public static FormLink<IMessageGetter> xMADESSiegeModeCannotDeactivateMessage => Construct(0x1404a6);
            public static FormLink<IMessageGetter> xMACONGatesOfOblivionNoMoreDaedraMessage => Construct(0x1b4cf6);
            public static FormLink<IMessageGetter> xMACONGatesOfOblivionOnlyOneMessage => Construct(0x1b4cf8);
            public static FormLink<IMessageGetter> xMAILLLoseHopeFailedMessage => Construct(0x2c1537);
            public static FormLink<IMessageGetter> xMACONAddedNewVeinMessage => Construct(0x205e07);
            public static FormLink<IMessageGetter> xMACONBoneMasterySummonSpellMessage => Construct(0x3c8bce);
            public static FormLink<IMessageGetter> xMANotReadyNeedRestMessage => Construct(0x33fee6);
            public static FormLink<IMessageGetter> xMASPEBattleAnthemOnCooldown => Construct(0x3b476f);
            public static FormLink<IMessageGetter> xMAILLInsightMessage1 => Construct(0x3f6556);
            public static FormLink<IMessageGetter> xMASMIPlaceTrapMessageBox => Construct(0x3d7ef9);
            public static FormLink<IMessageGetter> xMASMIPlaceTrapNoTrapMessage => Construct(0x3dcffd);
            public static FormLink<IMessageGetter> xMAWAYWildCompanion0MessageBox => Construct(0x3e2112);
            public static FormLink<IMessageGetter> xMAWAYWildCompanion1MessageBox => Construct(0x3e2113);
            public static FormLink<IMessageGetter> xMAILLInsightMessage0 => Construct(0x3f6555);
            public static FormLink<IMessageGetter> xMAENCGreatInfusionMessageAlreadyRunning => Construct(0x419cae);
            public static FormLink<IMessageGetter> xMAILLInsightMessage2 => Construct(0x3f6557);
            public static FormLink<IMessageGetter> xMAILLInsightMessage3 => Construct(0x3f6558);
            public static FormLink<IMessageGetter> xMAILLInsightMessage4 => Construct(0x3f6559);
            public static FormLink<IMessageGetter> xMAILLInsightMessage5 => Construct(0x3f655a);
            public static FormLink<IMessageGetter> xMAILLInsightMessage6 => Construct(0x3f655b);
            public static FormLink<IMessageGetter> xMAWAYShapeshifterChooseShapeMessage => Construct(0x40077a);
            public static FormLink<IMessageGetter> xMAStillHavePerksToSpendMessage => Construct(0x3f656f);
            public static FormLink<IMessageGetter> xMAENCGreatInfusionMessageNoDragonSouls => Construct(0x419cab);
            public static FormLink<IMessageGetter> xMAENCGreatInfusionMessageFinished => Construct(0x419caf);
            public static FormLink<IMessageGetter> xMASNEShadowboundReadyMessage => Construct(0x5a9e8c);
            public static FormLink<IMessageGetter> xMAALTKineticCooldownMessage => Construct(0x4cd090);
            public static FormLink<IMessageGetter> xMAWAYWildCompanionAlreadyGotAnimalMessage => Construct(0x4cb09f);
            public static FormLink<IMessageGetter> xMAALTShiftOnCooldownMessage => Construct(0x4ce23);
            public static FormLink<IMessageGetter> xMASPELeadershipMessageNoMoney => Construct(0x183c);
            public static FormLink<IMessageGetter> xMASNEArcaneAssassinMessage => Construct(0x23373);
            public static FormLink<IMessageGetter> xMASNESpellSneakMessage => Construct(0xbd97);
            public static FormLink<IMessageGetter> xMASPELeadershipMessageTooManySameKind => Construct(0x183d);
            public static FormLink<IMessageGetter> xMASPELeadershipMessageTooManyMercenaries => Construct(0x183e);
            public static FormLink<IMessageGetter> xMASPELeadershipMessageBox => Construct(0x12ca);
            public static FormLink<IMessageGetter> xMADESabsolutezeroToggleOffMessage => Construct(0x739f5c);
        }
    }
}
