// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class MiscItem
        {
            private static FormLink<IMiscItemGetter> Construct(uint id) => new FormLink<IMiscItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMiscItemGetter> xMAEasterEggFeathertop => Construct(0x6747d0);
            public static FormLink<IMiscItemGetter> xMACONBoneArm => Construct(0x705d2);
            public static FormLink<IMiscItemGetter> xMACONBoneFoot => Construct(0x705d3);
            public static FormLink<IMiscItemGetter> xMACONBoneHand => Construct(0x705d4);
            public static FormLink<IMiscItemGetter> xMACONBoneLeg => Construct(0x705d5);
            public static FormLink<IMiscItemGetter> xMACONBoneRibcage => Construct(0x705d6);
            public static FormLink<IMiscItemGetter> xMACONBoneSkull => Construct(0x705d7);
            public static FormLink<IMiscItemGetter> xMAWAYBearPeltQuality => Construct(0x8fd33);
            public static FormLink<IMiscItemGetter> xMAWAYBearCavePeltQuality => Construct(0x8fd32);
            public static FormLink<IMiscItemGetter> xMAWAYBearSnowPeltQuality => Construct(0x8fd34);
            public static FormLink<IMiscItemGetter> xMASNEGlazedCandles01_OFF => Construct(0x71845);
            public static FormLink<IMiscItemGetter> xMAWAYDeerPeltQuality => Construct(0x8fd35);
            public static FormLink<IMiscItemGetter> xMAWAYFoxPeltQuality => Construct(0x8fd36);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenSpiderMediContainer => Construct(0xa82a2);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenSpiderContainer => Construct(0xa82a1);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenSphereContainer => Construct(0xa82a0);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenCenturionSteamContainer => Construct(0xa829f);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenCenturionFrostContainer => Construct(0xa829e);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenCenturionFireContainer => Construct(0xa829d);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenBallistaContainer => Construct(0xa829c);
            public static FormLink<IMiscItemGetter> xMAWAYWolfPeltQuality => Construct(0x8fd39);
            public static FormLink<IMiscItemGetter> xMAALCPoisonArmorPhial => Construct(0x1088e7);
            public static FormLink<IMiscItemGetter> xMAWAYSabreCatPeltQuality => Construct(0x8fd37);
            public static FormLink<IMiscItemGetter> xMAWAYSabreCatSnowPeltQuality => Construct(0x8fd38);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBear => Construct(0x19ad21);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapSpikes => Construct(0x1a23fd);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBearPoison => Construct(0x1a2400);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBearExplosive => Construct(0x1a240a);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBearFire => Construct(0x1a2414);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBearFrost => Construct(0x1a2415);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBearShock => Construct(0x1a2416);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapBearParalysis => Construct(0x1a2417);
            public static FormLink<IMiscItemGetter> xMASMIHuntingGroundsTrapSpikesPoison => Construct(0x1c2765);
            public static FormLink<IMiscItemGetter> xMAALCFieldAlchemyAlembic => Construct(0x286109);
            public static FormLink<IMiscItemGetter> xMADEXInventor1TripwireBond => Construct(0x372983);
            public static FormLink<IMiscItemGetter> xMADEXInventor1SpikePowder => Construct(0x37298b);
            public static FormLink<IMiscItemGetter> xMADEXInventor2Spellbomb => Construct(0x37298e);
            public static FormLink<IMiscItemGetter> xMADEXInventor0Fingertrap => Construct(0x377a97);
            public static FormLink<IMiscItemGetter> xMADEXInventor0SemiconductiveDevice => Construct(0x377a9f);
            public static FormLink<IMiscItemGetter> xMADEXInventor2OilContainer => Construct(0x3be993);
            public static FormLink<IMiscItemGetter> xMASMICopycatArtifactEssence => Construct(0x4331e5);
            public static FormLink<IMiscItemGetter> xMAEnchantersQuill => Construct(0x47f159);
            public static FormLink<IMiscItemGetter> xMAWAYQualityLeatherStrips => Construct(0x44761e);
            public static FormLink<IMiscItemGetter> xMALightweightFiller => Construct(0x493562);
            public static FormLink<IMiscItemGetter> xMACrossbowModificationKit => Construct(0x43d417);
            public static FormLink<IMiscItemGetter> xMAWAYQualityLeather => Construct(0x44761d);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenSphereContainerBroken => Construct(0x5d77a3);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenCenturionSteamContainerBroken => Construct(0x5d77a2);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenSpiderMediContainerBroken => Construct(0x5d77a4);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenBallistaContainerBroken => Construct(0x5d779f);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenCenturionFireContainerBroken => Construct(0x5d77a0);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenCenturionFrostContainerBroken => Construct(0x5d77a1);
            public static FormLink<IMiscItemGetter> xMASMIDwarvenSpiderContainerBroken => Construct(0x5d77a5);
            public static FormLink<IMiscItemGetter> xMAENCMasteryBlocker => Construct(0xd903c8);
        }
    }
}
