// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class MoveableStatic
        {
            private static FormLink<IMoveableStaticGetter> Construct(uint id) => new FormLink<IMoveableStaticGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMoveableStaticGetter> xMASNETESTCandleFlame01_OFF => Construct(0x7184f);
            public static FormLink<IMoveableStaticGetter> xMASNECampfire01LandBurningSnow => Construct(0x7027d);
        }
    }
}
