// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class ObjectEffect
        {
            private static FormLink<IObjectEffectGetter> Construct(uint id) => new FormLink<IObjectEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IObjectEffectGetter> xMASMIMasteryWarforgedEnchWeapon => Construct(0x61e64b);
            public static FormLink<IObjectEffectGetter> xMASMIMasteryWarforgedEnchArmor => Construct(0x61e64c);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorRegenStaminaMagickaBase => Construct(0x641d5f);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorRegenStaminaMagicka0 => Construct(0x641d60);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorRegenStaminaMagicka1 => Construct(0x641d62);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorRegenStaminaMagicka2 => Construct(0x641d64);
            public static FormLink<IObjectEffectGetter> xMAEasterEggMaskNerjalEnch => Construct(0x6b650b);
            public static FormLink<IObjectEffectGetter> xMAALCPoisonBurstAmmoPoisonExplosionENCH => Construct(0x73f061);
            public static FormLink<IObjectEffectGetter> xMAALCFlareUndead00Enchantment => Construct(0x3878);
            public static FormLink<IObjectEffectGetter> xMAALCCorrodeArmor00Enchantment => Construct(0x23975);
            public static FormLink<IObjectEffectGetter> xMASNEIdentityConcealingMaskEnch => Construct(0x8ed39);
            public static FormLink<IObjectEffectGetter> EnchArchmageRobe => Construct(0xb6c48);
            public static FormLink<IObjectEffectGetter> xMACONBoundBattleaxeEnchantment => Construct(0x1c912b);
            public static FormLink<IObjectEffectGetter> xMACONBoundBowEnchantment => Construct(0x1c912e);
            public static FormLink<IObjectEffectGetter> xMACONBoundDaggerEnchantment => Construct(0x1c9131);
            public static FormLink<IObjectEffectGetter> xMACONBoundSwordEnchantment => Construct(0x1c9132);
            public static FormLink<IObjectEffectGetter> xMADESFrostFrostRuneEnch => Construct(0x21f34b);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorFortifySmithing => Construct(0x2661ed);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorFortifyAlchemy => Construct(0x2661f0);
            public static FormLink<IObjectEffectGetter> xMAEmptyStaffEnch => Construct(0x27f702);
            public static FormLink<IObjectEffectGetter> xMAALCPoisonBurstProjectileExplosion => Construct(0x28ea46);
            public static FormLink<IObjectEffectGetter> xMAALCElementalBurstEnchFire => Construct(0x28ea4b);
            public static FormLink<IObjectEffectGetter> xMAALCElementalBurstEnchShock => Construct(0x28ea4e);
            public static FormLink<IObjectEffectGetter> xMAALCElementalBurstEnchFrost => Construct(0x28ea52);
            public static FormLink<IObjectEffectGetter> xMAILLInfluenceFrenzyRuneProjectileExplosionEnch => Construct(0x2e4c4a);
            public static FormLink<IObjectEffectGetter> xMARANAdvancedMissilecraft1BarbedEnch => Construct(0x405883);
            public static FormLink<IObjectEffectGetter> xMAENCGreatInfusionEnchWeapon => Construct(0x40a98e);
            public static FormLink<IObjectEffectGetter> xMAENCGreatInfusionEnchArmor => Construct(0x40a98f);
            public static FormLink<IObjectEffectGetter> xMAEnchWeaponDiseaseDamage0 => Construct(0x5dc8af);
            public static FormLink<IObjectEffectGetter> xMAEnchWeaponDiseaseDamageBase => Construct(0x5dc8b1);
            public static FormLink<IObjectEffectGetter> xMAEnchWeaponDiseaseDamage1 => Construct(0x5dc8b3);
            public static FormLink<IObjectEffectGetter> xMAEnchWeaponDiseaseDamage2 => Construct(0x5dc8b5);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorResistPoisonDisease0 => Construct(0x5dc8b9);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorResistPoisonDiseaseBase => Construct(0x5dc8ba);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorResistPoisonDisease1 => Construct(0x5dc8bc);
            public static FormLink<IObjectEffectGetter> xMAEnchArmorResistPoisonDisease2 => Construct(0x5dc8be);
        }
    }
}
