// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Package
        {
            private static FormLink<IPackageGetter> Construct(uint id) => new FormLink<IPackageGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IPackageGetter> xMAMercenaryRangePackage => Construct(0x3e2104);
            public static FormLink<IPackageGetter> xMASNEMercenary01Package => Construct(0x644f9);
            public static FormLink<IPackageGetter> xMAMercenaryMeleePackage => Construct(0x3e2103);
            public static FormLink<IPackageGetter> xMASNEHorstarNightTimePackage => Construct(0x63f94);
            public static FormLink<IPackageGetter> xMASNEHorstarDayTimePackage => Construct(0x63f93);
        }
    }
}
