// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Projectile
        {
            private static FormLink<IProjectileGetter> Construct(uint id) => new FormLink<IProjectileGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IProjectileGetter> xMAALTKineticShiftProjectile => Construct(0x5704c);
            public static FormLink<IProjectileGetter> xMASNEMeasureDistanceProjectile => Construct(0x58fff);
            public static FormLink<IProjectileGetter> xMASNEWaterArrowProjectile => Construct(0x6dbcf);
            public static FormLink<IProjectileGetter> xMAALTArtificialSunProjectile => Construct(0x70608);
            public static FormLink<IProjectileGetter> xMAALTArtificialSunLightProjectile => Construct(0x7060f);
            public static FormLink<IProjectileGetter> xMAALTArtificialSunMIssileProjectile => Construct(0x70610);
            public static FormLink<IProjectileGetter> xMAALTSunburstRemainsProjectile => Construct(0x7a86b);
            public static FormLink<IProjectileGetter> xMADESImplosionFireballProjectile => Construct(0x84a79);
            public static FormLink<IProjectileGetter> xMASNEFireArrowProjectile => Construct(0x8a735);
            public static FormLink<IProjectileGetter> xMASNENoisemakerArrowProjectile => Construct(0x8d249);
            public static FormLink<IProjectileGetter> xMASNEOilArrowProjectile => Construct(0x91daf);
            public static FormLink<IProjectileGetter> xMADESFrostFrostFieldProjectile => Construct(0x98efb);
            public static FormLink<IProjectileGetter> xMADESFrostFrostFieldIceSpikeSpellProjectile => Construct(0x98eff);
            public static FormLink<IProjectileGetter> xMASNEFindGroundOilProjectile => Construct(0x9da23);
            public static FormLink<IProjectileGetter> xMASNEFindGroundOilProjectileMaster => Construct(0x9df88);
            public static FormLink<IProjectileGetter> xMASNEFireBoltProjectile => Construct(0xabc5c);
            public static FormLink<IProjectileGetter> xMASNENoisemakerBoltProjectile => Construct(0xabc5d);
            public static FormLink<IProjectileGetter> xMASNEOilBoltProjectile => Construct(0xabc5e);
            public static FormLink<IProjectileGetter> xMASNERopeBoltProjectile => Construct(0xabc5f);
            public static FormLink<IProjectileGetter> xMASNEWaterBoltProjectile => Construct(0xabc60);
            public static FormLink<IProjectileGetter> xMADESMixedHeavenlapseFireSpellProjectile => Construct(0xd5e66);
            public static FormLink<IProjectileGetter> xMADESMixedHeavenlapseFrostSpellProjectile => Construct(0xd5e67);
            public static FormLink<IProjectileGetter> xMADESMixedHeavenlapseShockSpellProjectile => Construct(0xd5e68);
            public static FormLink<IProjectileGetter> xMARESCurseProjectile => Construct(0xdaf70);
            public static FormLink<IProjectileGetter> xMADESMixedArcticBlazeFireSpellProjectile => Construct(0xdaf71);
            public static FormLink<IProjectileGetter> xMADESMixedArcticBlazeFrostSpellProjectile => Construct(0xdaf72);
            public static FormLink<IProjectileGetter> xTESTProjectilePROJ => Construct(0xdaf7a);
            public static FormLink<IProjectileGetter> xMATESTHugeFireboltProjectile => Construct(0x1548c3);
            public static FormLink<IProjectileGetter> xMADESVolcanicOrbProjectile => Construct(0x1548c4);
            public static FormLink<IProjectileGetter> xMACONGatesOfOblivionFlavourSpellProjectile => Construct(0x182239);
            public static FormLink<IProjectileGetter> xMACONGatesOfOblivionProjectile => Construct(0x182241);
            public static FormLink<IProjectileGetter> xMADESMixedPyroelectricOrbProjectile => Construct(0x1aaae7);
            public static FormLink<IProjectileGetter> xMACONSummonUnboundFlameAtronachProjectile => Construct(0x1b9e00);
            public static FormLink<IProjectileGetter> xMACONSummonUnboundFrostAtronachProjectile => Construct(0x1b9e01);
            public static FormLink<IProjectileGetter> xMACONSummonUnboundStormAtronachProjectile => Construct(0x1b9e02);
            public static FormLink<IProjectileGetter> xMAALTInverseShiftProjectile => Construct(0x1d3342);
            public static FormLink<IProjectileGetter> xMAILLMindPrisonProjectile => Construct(0x1d844c);
            public static FormLink<IProjectileGetter> xMADESFrostFrostRuneProjectile => Construct(0x21f34d);
            public static FormLink<IProjectileGetter> xMADESFireRuneProjectile => Construct(0x21f34f);
            public static FormLink<IProjectileGetter> xMADESShockLightningRuneProjectile => Construct(0x21f351);
            public static FormLink<IProjectileGetter> xMAILLInfluenceFrenzyRuneProjectile => Construct(0x2e4c49);
            public static FormLink<IProjectileGetter> xMADESMixedPrismaticBeamProjectile => Construct(0x30d493);
            public static FormLink<IProjectileGetter> xMASMIPlaceTrapProjectile => Construct(0x3dcffe);
            public static FormLink<IProjectileGetter> xMADESFireHeavyFireballEffectProjectile => Construct(0x507cfc);
            public static FormLink<IProjectileGetter> xMARANMasterySkillshotSpellEffectProjectile => Construct(0xd62aac);
            public static FormLink<IProjectileGetter> xMADESFrostFrostburnEffect0Projectile => Construct(0x52b44b);
            public static FormLink<IProjectileGetter> xMADESMixedBlueFlamesProjectile => Construct(0x535661);
            public static FormLink<IProjectileGetter> xMADESMixedHellfireCageShockSpellProjectile => Construct(0x54eb81);
            public static FormLink<IProjectileGetter> xMAENCArcaneArcheryGreatFireballSpellEffectProjectile => Construct(0x59fc87);
            public static FormLink<IProjectileGetter> xMAENCArcaneArcheryThunderstrikeSpellEffectProjectile => Construct(0x59fc88);
            public static FormLink<IProjectileGetter> xMAENCArcaneArcheryWintersBreathSpellEffect0Projectile => Construct(0x59fc89);
            public static FormLink<IProjectileGetter> xMAILLDeliriumProjectile => Construct(0x641d66);
            public static FormLink<IProjectileGetter> xMAILLConfusionProjectile => Construct(0x641d6c);
            public static FormLink<IProjectileGetter> xMAALTSpellPrismEffectProjectile => Construct(0x67e9de);
            public static FormLink<IProjectileGetter> xMACONDeathThrallEffectProjectile => Construct(0x6ca915);
            public static FormLink<IProjectileGetter> xMASNERopeArrowProjectile => Construct(0x4e3a2);
            public static FormLink<IProjectileGetter> xMAALTCombatShiftProjectile => Construct(0x51f2d);
            public static FormLink<IProjectileGetter> xMAALTPhaseShiftProjectile => Construct(0x51f33);
        }
    }
}
