// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Quest
        {
            private static FormLink<IQuestGetter> Construct(uint id) => new FormLink<IQuestGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IQuestGetter> xMAQuestConjuration => Construct(0x10092);
            public static FormLink<IQuestGetter> xMASharedScriptContainerQuest => Construct(0x1f427);
            public static FormLink<IQuestGetter> xMAQuestIllusion => Construct(0x10091);
            public static FormLink<IQuestGetter> xMAQuestBlock => Construct(0xfe6cf);
            public static FormLink<IQuestGetter> xMAQuestAlteration => Construct(0x10094);
            public static FormLink<IQuestGetter> xMAQuestRestoration => Construct(0x1008f);
            public static FormLink<IQuestGetter> xMAQuestDestruction => Construct(0x10090);
            public static FormLink<IQuestGetter> xMAQuestHeavyArmor => Construct(0x3c8bcc);
            public static FormLink<IQuestGetter> xMAQuestSneak => Construct(0xd63);
            public static FormLink<IQuestGetter> xMAQuestLightWeaponry => Construct(0x34f1ff);
            public static FormLink<IQuestGetter> xMAQuestHeavyWeaponry => Construct(0x34f202);
            public static FormLink<IQuestGetter> xMAQuestWayfarer => Construct(0xfe6d4);
            public static FormLink<IQuestGetter> xMAQuestSmithing => Construct(0x5c15e);
            public static FormLink<IQuestGetter> xMASNEAliasesQuest => Construct(0x7232c);
            public static FormLink<IQuestGetter> xMAQuestAlchemy => Construct(0x1088f3);
            public static FormLink<IQuestGetter> xMAQuestRangedWeaponry => Construct(0x34f203);
            public static FormLink<IQuestGetter> xMAQuestSpeechcraft => Construct(0x3125a2);
            public static FormLink<IQuestGetter> xMAQuestEnchanting => Construct(0x10093);
            public static FormLink<IQuestGetter> xMAQuestLightArmor => Construct(0x3b9887);
            public static FormLink<IQuestGetter> xMAQuestDexterity => Construct(0x117c26);
        }
    }
}
