// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Relationship
        {
            private static FormLink<IRelationshipGetter> Construct(uint id) => new FormLink<IRelationshipGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate7 => Construct(0x590d);
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate6 => Construct(0x590c);
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate5 => Construct(0x590b);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate => Construct(0x3d466);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate2 => Construct(0x3d467);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate3 => Construct(0x3d468);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate4 => Construct(0x3d469);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate5 => Construct(0x3d46a);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate6 => Construct(0x3d46b);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate7 => Construct(0x3d46c);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate11 => Construct(0x3d470);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate10 => Construct(0x3d46f);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate9 => Construct(0x3d46e);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate8 => Construct(0x3d46d);
            public static FormLink<IRelationshipGetter> AnimalFollower_Player_Relate12 => Construct(0x3d471);
            public static FormLink<IRelationshipGetter> UndeadFollower_Player_Relate => Construct(0x3d472);
            public static FormLink<IRelationshipGetter> UndeadFollower_Player_Relate2 => Construct(0x3d473);
            public static FormLink<IRelationshipGetter> UndeadFollower_Player_Relate3 => Construct(0x3d474);
            public static FormLink<IRelationshipGetter> UndeadFollower_Player_Relate4 => Construct(0x5904);
            public static FormLink<IRelationshipGetter> UndeadFollower_Player_Relate5 => Construct(0x5905);
            public static FormLink<IRelationshipGetter> UndeadFollower_Player_Relate6 => Construct(0x5906);
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate => Construct(0x5907);
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate2 => Construct(0x5908);
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate3 => Construct(0x5909);
            public static FormLink<IRelationshipGetter> DwarvenFollower_Player_Relate4 => Construct(0x590a);
        }
    }
}
