// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class TextureSet
        {
            private static FormLink<ITextureSetGetter> Construct(uint id) => new FormLink<ITextureSetGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ITextureSetGetter> xMACONBeastHeartTEXT => Construct(0x3af664);
            public static FormLink<ITextureSetGetter> xMACONElvenHeartTEXT => Construct(0x3af665);
            public static FormLink<ITextureSetGetter> xMACONBeastFleshTEXT => Construct(0x3c3ab3);
            public static FormLink<ITextureSetGetter> xMACONElvenFleshTEXT => Construct(0x3c3ab4);
            public static FormLink<ITextureSetGetter> xMASMIDwemerContainerTier1TXST => Construct(0x49d767);
            public static FormLink<ITextureSetGetter> xMASMIDwemerContainerTier2TXST => Construct(0x49d768);
            public static FormLink<ITextureSetGetter> xMASMIDwemerContainerTier3TXST => Construct(0x49d769);
            public static FormLink<ITextureSetGetter> xMACONSkeletonOverlordArcherTEXT => Construct(0x4d01a6);
            public static FormLink<ITextureSetGetter> xMACONSkeletonOverlordWarriorTEXT => Construct(0x4d01a7);
            public static FormLink<ITextureSetGetter> xMACONSkeletonOverlordMageTEXT => Construct(0x4d01a8);
            public static FormLink<ITextureSetGetter> xMADEXInventor0SemiconductiveDeviceTEXT => Construct(0x4f38e6);
            public static FormLink<ITextureSetGetter> xMADEXInventor1SpikePowderTEXT => Construct(0x4f38e7);
            public static FormLink<ITextureSetGetter> xMADEXInventor2OilContainerTEXT => Construct(0x4f38e8);
            public static FormLink<ITextureSetGetter> xMADEXInventor0FingerTrapTEXT => Construct(0x562fa9);
            public static FormLink<ITextureSetGetter> xMASMIDwemerContainerTier1BrokenTXST => Construct(0x5d779c);
            public static FormLink<ITextureSetGetter> xMASMIDwemerContainerTier2BrokenTXST => Construct(0x5d779d);
            public static FormLink<ITextureSetGetter> xMASMIDwemerContainerTier3BrokenTXST => Construct(0x5d779e);
            public static FormLink<ITextureSetGetter> xMAEasterEggMaskNerjalTEXT => Construct(0x6bb60d);
            public static FormLink<ITextureSetGetter> xMAALTSpellPrismTEXT => Construct(0x6bb60e);
            public static FormLink<ITextureSetGetter> xMAEasterEggMaskNerjalHoodTEXT => Construct(0x6bb610);
            public static FormLink<ITextureSetGetter> xMASNEOilDecals => Construct(0x9a44b);
            public static FormLink<ITextureSetGetter> xMAALCPoisonArmorPhialTEXT => Construct(0x14f7c1);
            public static FormLink<ITextureSetGetter> xMACONGatesOfOblivionGateTEXT => Construct(0x17d133);
        }
    }
}
