// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Master
    {
        public static class Tree
        {
            private static FormLink<ITreeGetter> Construct(uint id) => new FormLink<ITreeGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ITreeGetter> xMATreeReachBush02 => Construct(0x1a2ed);
            public static FormLink<ITreeGetter> xMATreeReachShrub02 => Construct(0x1a2f1);
            public static FormLink<ITreeGetter> xMATreeReachTree01 => Construct(0x1a2f0);
            public static FormLink<ITreeGetter> xMATreeReachFern03 => Construct(0x1a2ef);
            public static FormLink<ITreeGetter> xMATreeReachBush01 => Construct(0x1a2ec);
            public static FormLink<ITreeGetter> xMATreeReachFern01 => Construct(0x1a2ee);
        }
    }
}
