// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class PerkusMaximus_Thief
    {
        public static class GameSetting
        {
            private static FormLink<IGameSettingGetter> Construct(uint id) => new FormLink<IGameSettingGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IGameSettingGetter> fLockpickBreakSkillMult => Construct(0x29008);
            public static FormLink<IGameSettingGetter> fCombatStealthPointRegenAlertWaitTime => Construct(0x60b14);
            public static FormLink<IGameSettingGetter> iCrimeAlarmLowRecDistance => Construct(0x60b15);
            public static FormLink<IGameSettingGetter> iCrimeAlarmRecDistance => Construct(0x60b16);
        }
    }
}
